import "./globals.css";

export const metadata = {
  title: "Dropdrop",
  description: "Generated by create next app",
  icon: "/deal-drop-logo.png",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>{children}</body>
    </html>
  );
}
